# Generated by Django 4.1.7 on 2023-08-10 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_product_prodapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('KT', 'Kurta'), ('AB', 'Abhaya'), ('AN', 'Anarkali'), ('CH', 'Churitar'), ('ST', 'shirt')], max_length=2),
        ),
    ]
