# Generated by Django 4.1.7 on 2023-08-16 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('KT', 'Kurta'), ('AB', 'Abhaya'), ('AN', 'Anarkali'), ('CH', 'Churitar'), ('ST', 'Shirt'), ('Sv', 'Sherwani')], max_length=2),
        ),
    ]
